### ISSUE TITLE
Pressing u then clicking on melter and crashing

### ISSUE THREAD

**Issue by Munchy907** [Laskyyy/Create-Astral#91] opened 2023-04-09 01:43 UTC
Cannot reproduce it, but here's the crash log 

[crash-2023-04-09_03.36.15-client.txt](https://github.com/Laskyyy/Create-Astral/files/11184619/crash-2023-04-09_03.36.15-client.txt)

**Comment by Erdragh** [comment] 2023-05-24 05:13
Closing this because it can't be reproduced. If you can find a reliable way to reproduce the issue, please reopen the issue.

**Closed by Erdragh** 2023-05-24 05:13 UTC
Labels: bug
