### ISSUE TITLE
Beds stopped working

### ISSUE THREAD

**Issue by BellaMagick** [Laskyyy/Create-Astral#61] opened 2023-03-21 04:10 UTC
Game was working great, and then after the pack updated the game would load and play but then the beds would stop working. You break the bed and move it and still can use the bed to sleep. I un installed the pack and re installed the pack, and I also copy my world and started a new one and the bed issue is still there.

**Comment by Tsuppo** [comment] 2023-03-25 13:11
I am also having this issue. Nothing happens when I try to sleep, not even the use animation.

**Comment by BellaMagick** [comment] 2023-03-25 17:46
I have found a way around the bed problem by having a tool in my hand. When its time to sleep I just click the bed with the tool in hand and I sleep.

**Comment by Erdragh** [comment] 2023-05-24 05:18
This is most likely a duplicate of #75 and as such is caused by the Travellers Armor. As tinkers 1.18.2 fabric is not getting updates anymore, I will close this issue as not planned. If anybody finds a fix please reopen this issue and share said fix.

**Closed by Erdragh** 2023-05-24 05:19 UTC
Labels: bug
