### ISSUE TITLE
Issue with sleeping in beds

### ISSUE THREAD

**Issue by Sir-Antonic** [Laskyyy/Create-Astral#75] opened 2023-03-28 15:45 UTC
There seem to be some problems with Astral v2.0.3 that prevent me from right-clicking on a newly placed bed to sleep. Strangely, I don't have this issue when using a bed from a village or the one I previously placed in my base. The new ones I craft or pick up simply won't respond to right-clicking and won't show any indication of being set as a spawn point.

I'm attaching a gif to "show" the issue

https://imgur.com/pB5tS5Y

**Comment by Sir-Antonic** [comment] 2023-03-28 15:53
Upon some experimentation, I discovered that after my character was attacked by a zombie and I subsequently killed it, I was able to right-click the bed for some inexplicable reason. Unfortunately, I wasn't able to record this occurrence. It remains unclear whether it was specifically that action or some other variable that enabled me to interact with the bed in this way.

**Comment by Sir-Antonic** [comment] 2023-03-28 18:09
After conducting further experiments, I have determined that this issue appears to be isolated to instances where I attempt to utilize my bare hand. Interestingly, when I employ a tool or other object, clicking on the bed presents no difficulty whatsoever. At this juncture, I remain uncertain as to whether this anomaly is attributed to the bed itself or the traveler's armor I am utilizing.

**Comment by timingplanet** [comment] 2023-03-30 00:21
Ive had this issue a lot. Crouching on said bed and right clicking seems to be the only way for it to work for me.

**Comment by Erdragh** [comment] 2023-05-24 05:16
This is a known issue caused by the Travellers Armor. However, as Tinkers is not getting updated anymore for fabric 1.18.2 there's not all that much that we can do.

As such I'll close this issue as not planned.

**Closed** 2023-05-24 05:16 UTC
Labels: bug
