### ISSUE TITLE
GLFW error 65539: Invalid Key 4

### ISSUE THREAD

**Issue by DenuxPlays** [Laskyyy/Create-Astral#109] opened 2023-04-14 13:55 UTC
Hey,
every time when I try to start the game I get the following error:
![image](https://user-images.githubusercontent.com/83671398/232063425-a7556f58-c995-418f-ae84-eb5f92e7ee1d.png)

Stacktrace:
![image](https://user-images.githubusercontent.com/83671398/232064417-68076889-ef6a-4258-8ca8-d0ce7f2c6931.png)

##  First Workaround
delete the `options.txt` file 

## second Workaround
delete mouse.4 and mouse.5 keys inside your `options.txt` file

This is more than annoying. When I want to play I have to atleast take 15min to remap every control which is pretty annoying.

**Comment by Laskyyy** [comment] 2023-04-14 16:25
What version, this should be fixed with a band-aid in 2.0.4 (removed any default mappings for mouse buttons)

It is caused by cams backpacks, and such will require an upcoming update before a total fix!

**Comment by DenuxPlays** [comment] 2023-04-16 11:50
> What version, this should be fixed with a band-aid in 2.0.4 (removed any default mappings for mouse buttons)
> 
> It is caused by cams backpacks, and such will require an upcoming update before a total fix!

Could you please release a new version with the fix?

**Closed** 2023-05-07 23:16 UTC
